<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['useragent']        = 'MMPI';    
$config['protocol']         = 'smtp';        
$config['mailpath']         = '/usr/sbin/sendmail';
$config['smtp_host']        = 'smtp.mandrillapp.com';
$config['smtp_user']        = 'mmpi.vchpi@gmail.com';
$config['smtp_pass']        = 'twQdpesZFEJrdhn_RiW0wA';
$config['smtp_port']        = 587;
$config['smtp_timeout']     = 5;
$config['wordwrap']         = TRUE;
$config['wrapchars']        = 76;
$config['mailtype']         = 'html';
$config['charset']          = 'iso-8859-1';
$config['validate']         = FALSE;
$config['priority']         = 3;
$config['crlf']             = "\r\n";
$config['newline']          = "\r\n";
$config['bcc_batch_mode']   = FALSE;
$config['bcc_batch_size']   = 200;
